#' @title transfrom html file generated by wowslider
#'
#' @return `NULL`
#' @export
modify_html <- function() {
    suppressWarnings(html <- readr::read_lines('wowslider.html'));

    html[1] = '<!DOCTYPE html>';

    html = stringr::str_replace_all(html, 'data1/images/', '../image/Team 1000 750/');


    html = stringr::str_replace(html, '<div class="ws_script"[\\w\\W]*?</div>', '');

    readr::write_lines(html, 'index.html')

    NULL;
}

#' @title transfrom css file generated by wowslider
#'
#' @return `NULL`
#' @export
modify_css <- function() {
    suppressWarnings(css <- readr::read_lines('engine1/style.css'));

    css <- stringr::str_replace(css, './bullet.png',
                       paste0('data:image/png;base64,', base64enc::base64encode('engine1/bullet.png')))

    css <- stringr::str_replace(css, './arrows.png',
                       paste0('data:image/png;base64,', base64enc::base64encode('engine1/arrows.png')))

    css <- stringr::str_replace(css, './arrows.gif',
                       paste0('data:image/gif;base64,', base64enc::base64encode('engine1/arrows.gif')))


    readr::write_lines(css, 'engine1/style.css');

    NULL;
}
